# Generated by Django 4.1.7 on 2023-03-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0002_alter_departments_options"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employees",
            options={"verbose_name": "Employee", "verbose_name_plural": "Employees"},
        ),
        migrations.AddField(
            model_name="employees",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="departments.departments",
            ),
        ),
    ]
