# Generated by Django 4.1.7 on 2023-03-30 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0003_rename_departments_department"),
        ("employees", "0002_alter_employees_options_employees_department"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employees",
            new_name="Employee",
        ),
    ]
