# Generated by Django 4.1.7 on 2023-03-30 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_alter_employees_options_employees_department"),
        ("departments", "0002_alter_departments_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Departments",
            new_name="Department",
        ),
    ]
